<<<<<<< HEAD
import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
=======
// This is a server component file (no "use client")
import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import RootLayout from "@/components/RootLayout"; // Move RootLayout to client component
>>>>>>> 2716a2abf474b7ed667d7a33a29716bde4b90774

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
});

<<<<<<< HEAD
=======
// Server-side metadata
>>>>>>> 2716a2abf474b7ed667d7a33a29716bde4b90774
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>{children}</body>
=======
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <RootLayout>{children}</RootLayout>
      </body>
>>>>>>> 2716a2abf474b7ed667d7a33a29716bde4b90774
    </html>
  );
}
