// This is a server component file (no "use client")
import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import RootLayout from "@/components/RootLayout"; // Move RootLayout to client component

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Server-side metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
